services:
  - type: web
    name: meetintel-agent
    env: node
    plan: free
    region: oregon
    branch: master
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
        required: true